version: "3.9"

services:
  server-backend:
    build: .
    container_name: server-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb-server
    networks:
      - private-net

  mongodb-server:
    image: mongo:latest
    container_name: mongodb-server
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    networks:
      - private-net

volumes:
  mongodb-data:

networks:
  private-net:
    driver: bridge
